### ISSUE TITLE
Add generalized absento

### ISSUE THREAD

**Issue by michaelballantyne** [michaelballantyne/faster-miniKanren#4]
Thoughts copied from https://github.com/michaelballantyne/faster-miniKanren/issues/2

`(absento a b)` is equivalent to: for all subtrees `s` of `b`, `(=/= a s)`. 

Applying `(absento a b)` where `a` and `b` are fresh logic variables should apply `(=/= a b)` and add `a` to the absento part of the constraint record for `b`. If `b` is instantiated to a pair `(c . d)`, we'll consult the constraint record and apply `(absento a c)` and `(absento a d)`, which will create the disequalities and add the absento constraint record to `c` and `d` just as we did with `b`.

Generalized absento still doesn't allow a constraint to restrict the range of values for a variable to a finite range, so it shouldn't break any of the assumptions that make the attributed variable implementation safe.

**Comment by webyrd** [comment]
Good point.

Okay, it sounds straight-forward to add, unless we are missing something.  Do you want to implement it, or do you prefer that I give it a shot?

**Comment by michaelballantyne** [comment]
If you're willing, that'd probably be best. I'm excited to finally have it
so that faster-miniKanren is no longer the incomplete ugly stepchild,
though! :)

**Comment by webyrd** [comment]
I'll give it a shot!  :)

I'm excited as well!

**Comment by jasonhemann** [comment]
Is this resolved? Which of you holds the now-canonical implementation of this repo?

**Comment by michaelballantyne** [comment]
I've merged Will's changes.
